/**
 * FW-07C-0 — Stable reason code registry for Forge WordPress enforcement.
 * Fail-closed admission uses codes only; free-text is supplementary.
 */

export const REASON_CODES = Object.freeze({
  FW_PATH_EMPTY: 'FW_PATH_EMPTY',
  FW_PATH_RELATIVE: 'FW_PATH_RELATIVE',
  FW_PATH_TRAVERSAL: 'FW_PATH_TRAVERSAL',
  FW_PATH_WILDCARD: 'FW_PATH_WILDCARD',
  FW_PATH_DRIVE_ROOT: 'FW_PATH_DRIVE_ROOT',
  FW_PATH_UNC_DENIED: 'FW_PATH_UNC_DENIED',
  FW_PATH_PROTECTED_ROOT: 'FW_PATH_PROTECTED_ROOT',
  FW_PATH_OUTSIDE_ALLOWED_ROOT: 'FW_PATH_OUTSIDE_ALLOWED_ROOT',
  FW_PATH_ROOT_MUTATION_DENIED: 'FW_PATH_ROOT_MUTATION_DENIED',
  FW_PATH_SOURCE_DESTINATION_EQUAL: 'FW_PATH_SOURCE_DESTINATION_EQUAL',
  FW_PATH_PARENT_CHILD_REVERSAL: 'FW_PATH_PARENT_CHILD_REVERSAL',
  FW_PATH_TRAILING_DOT: 'FW_PATH_TRAILING_DOT',
  FW_PATH_TRAILING_SPACE: 'FW_PATH_TRAILING_SPACE',
  FW_REPARSE_STATUS_REQUIRED: 'FW_REPARSE_STATUS_REQUIRED',
  FW_OPERATION_UNKNOWN: 'FW_OPERATION_UNKNOWN',
  FW_OPERATION_PHASE_DENIED: 'FW_OPERATION_PHASE_DENIED',
  FW_RISK_CLASS_DENIED: 'FW_RISK_CLASS_DENIED',
  FW_ENVIRONMENT_DENIED: 'FW_ENVIRONMENT_DENIED',
  FW_RUNTIME_BINDING_MISSING: 'FW_RUNTIME_BINDING_MISSING',
  FW_KILL_SWITCH_DISABLED: 'FW_KILL_SWITCH_DISABLED',
  FW_KILL_SWITCH_EMERGENCY: 'FW_KILL_SWITCH_EMERGENCY',
  FW_DRY_RUN_REQUIRED: 'FW_DRY_RUN_REQUIRED',
  FW_SNAPSHOT_REQUIRED: 'FW_SNAPSHOT_REQUIRED',
  FW_APPROVAL_REQUIRED: 'FW_APPROVAL_REQUIRED',
  FW_REQUEST_SCHEMA_INVALID: 'FW_REQUEST_SCHEMA_INVALID',
  FW_SITE_ID_MISSING: 'FW_SITE_ID_MISSING',
  FW_UNKNOWN_FIELD: 'FW_UNKNOWN_FIELD',
  FW_UNKNOWN_RISK_CLASS: 'FW_UNKNOWN_RISK_CLASS',
});

export const ALL_REASON_CODES = Object.freeze(Object.values(REASON_CODES));

export function isKnownReasonCode(code) {
  return ALL_REASON_CODES.includes(code);
}
