-- app_iseo_sales base tables (V1)
-- Prerequisites: core/0001, core/0002; roles from database/roles/001_create_roles.sql
-- Justified by forensics / ISEO-SALES-DATA-MODEL-v1 — not a 1:1 Sheets tab clone.

-- ---------------------------------------------------------------------------
-- 1) inbound_events (RAW intake)
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.inbound_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  source_system text NOT NULL DEFAULT 'gmail',
  source_id text NOT NULL, -- gmail_message_id
  gmail_thread_id text NULL,
  received_at timestamptz NULL,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  processing_status text NOT NULL DEFAULT 'received',
  processing_attempts int NOT NULL DEFAULT 0,
  correlation_id text NULL,
  lead_id text NULL,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_text text NULL,
  subject text NULL,
  from_email text NULL,
  normalized_hash text NULL,
  parser_version text NULL,
  workflow_version text NULL,
  parse_status text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_inbound_events PRIMARY KEY (id),
  CONSTRAINT uq_inbound_events_source UNIQUE (source_system, source_id),
  CONSTRAINT ck_inbound_events_processing_status CHECK (
    processing_status IN (
      'received', 'processing', 'processed', 'failed', 'deferred', 'skipped'
    )
  )
);

COMMENT ON TABLE app_iseo_sales.inbound_events IS
  'Durable Gmail/source intake (replaces lead_raw_v2 authority)';

-- ---------------------------------------------------------------------------
-- 2) leads (CLEAN current state)
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  lead_id text NOT NULL,
  inbound_event_id bigint NULL,
  source_message_id text NULL, -- gmail_message_id
  client_name text NULL,
  primary_contact text NULL,
  contact_type text NULL,
  phone text NULL,
  email text NULL,
  messenger text NULL,
  site text NULL,
  service text NULL,
  summary text NULL,
  source text NULL,
  request_page text NULL,
  utm_source text NULL,
  utm_medium text NULL,
  utm_campaign text NULL,
  processing_mode text NULL,
  ai_enabled boolean NULL,
  ai_status text NULL,
  ai_model text NULL,
  fallback_used boolean NULL,
  parser_version text NULL,
  message_format_version text NULL,
  reply_template_version text NULL,
  priority text NULL,
  quality_status text NULL,
  quality_comment text NULL,
  missing_fields text NULL,
  clarification_questions text NULL,
  manager_recommendation text NULL,
  first_reply_text text NULL,
  first_reply_source text NULL,
  reply_review_status text NULL,
  reply_sent_manually_at timestamptz NULL,
  duplicate_status text NULL,
  duplicate_match_type text NULL,
  duplicate_lead_id text NULL,
  previous_contact_at timestamptz NULL,
  previous_service text NULL,
  previous_summary text NULL,
  manager_status text NOT NULL DEFAULT 'new',
  assigned_to text NULL,
  first_contact_at timestamptz NULL,
  next_followup_at timestamptz NULL,
  closed_at timestamptz NULL,
  close_reason text NULL,
  manager_notes text NULL,
  processing_error text NULL,
  last_error_code text NULL,
  telegram_action_token text NULL,
  form_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  version int NOT NULL DEFAULT 1,
  data_contract_version text NULL,
  workflow_version text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_leads PRIMARY KEY (id),
  CONSTRAINT uq_leads_lead_id UNIQUE (lead_id),
  CONSTRAINT fk_leads_inbound_event
    FOREIGN KEY (inbound_event_id) REFERENCES app_iseo_sales.inbound_events (id),
  CONSTRAINT ck_leads_contact_type CHECK (
    contact_type IS NULL
    OR contact_type IN ('phone', 'email', 'messenger', 'mixed', 'unknown')
  ),
  CONSTRAINT ck_leads_duplicate_status CHECK (
    duplicate_status IS NULL
    OR duplicate_status IN ('new', 'reprocessed', 'repeat', 'possible')
  ),
  CONSTRAINT ck_leads_manager_status CHECK (
    manager_status IN (
      'new', 'pending', 'reviewing', 'contacted', 'waiting_client',
      'qualified', 'not_target', 'processed', 'spam', 'closed', 'error', 'reopened'
    )
  )
);

COMMENT ON TABLE app_iseo_sales.leads IS
  'Current manager-facing lead state (replaces lead_clean_v2 current row)';

CREATE UNIQUE INDEX uq_leads_source_message_id
  ON app_iseo_sales.leads (source_message_id)
  WHERE source_message_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 3) lead_dedup_keys (justified contact/message lookup — not a fake sheet clone)
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.lead_dedup_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  dedup_key text NOT NULL, -- format key_type:normalized_value
  key_type text NOT NULL,
  lead_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_lead_dedup_keys PRIMARY KEY (id),
  CONSTRAINT uq_lead_dedup_keys_dedup_key UNIQUE (dedup_key),
  CONSTRAINT fk_lead_dedup_keys_lead
    FOREIGN KEY (lead_id) REFERENCES app_iseo_sales.leads (lead_id),
  CONSTRAINT ck_lead_dedup_keys_key_type CHECK (
    key_type IN ('gmail_message_id', 'phone', 'email', 'messenger', 'site')
  )
);

COMMENT ON TABLE app_iseo_sales.lead_dedup_keys IS
  'Contact/message dedup lookup; justified domain index, not DEDUP_INDEX tab clone';

-- ---------------------------------------------------------------------------
-- 4) lead_events (immutable append-only)
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.lead_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  event_id text NULL,
  lead_id text NOT NULL,
  event_type text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  actor_type text NULL,
  actor_id text NULL,
  correlation_id text NULL,
  causation_id text NULL,
  workflow_version text NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- NO updated_at — immutable
  CONSTRAINT pk_lead_events PRIMARY KEY (id),
  CONSTRAINT uq_lead_events_event_id UNIQUE (event_id),
  CONSTRAINT fk_lead_events_lead
    FOREIGN KEY (lead_id) REFERENCES app_iseo_sales.leads (lead_id),
  CONSTRAINT ck_lead_events_actor_type CHECK (
    actor_type IS NULL
    OR actor_type IN ('system', 'moderator', 'admin', 'workflow', 'unknown')
  )
);

COMMENT ON TABLE app_iseo_sales.lead_events IS
  'Immutable domain history; runtime must INSERT/SELECT only (no UPDATE/DELETE)';

-- ---------------------------------------------------------------------------
-- 5) access_rules (ACCESS ACL — moderator identity lives here; no empty moderators table)
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.access_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  principal_key text NOT NULL, -- e.g. ADMIN_A / MOD_B
  telegram_user_id text NULL, -- sensitive but not a secret token; nullable for fixtures
  display_name text NULL,
  username text NULL,
  role text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  receives_cards boolean NOT NULL DEFAULT true,
  receives_reminders boolean NOT NULL DEFAULT true,
  reply_profile_number int NULL,
  telegram_chat_ref_hash text NULL, -- hashed ref, not token
  notes text NULL,
  revoked_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_access_rules PRIMARY KEY (id),
  CONSTRAINT uq_access_rules_principal_key UNIQUE (principal_key),
  CONSTRAINT ck_access_rules_role CHECK (role IN ('admin', 'moderator', 'viewer'))
);

COMMENT ON TABLE app_iseo_sales.access_rules IS
  'Staff ACL (ACCESS). V1: moderator/admin identity lives here — no separate moderators table. Do not store bot tokens or OAuth.';

-- ---------------------------------------------------------------------------
-- 6) deliveries (outbox)
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  delivery_id text NULL,
  lead_id text NULL,
  channel text NOT NULL DEFAULT 'telegram',
  recipient_principal_key text NULL,
  recipient_telegram_user_id text NULL,
  delivery_type text NOT NULL, -- lead_card, reminder, admin_notice, sync
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending',
  available_at timestamptz NOT NULL DEFAULT now(),
  attempts int NOT NULL DEFAULT 0,
  max_attempts int NOT NULL DEFAULT 8,
  sent_at timestamptz NULL,
  external_message_id text NULL, -- telegram_message_id
  telegram_chat_id text NULL,
  idempotency_key text NULL,
  last_error_id bigint NULL, -- FK added after errors table
  correlation_id text NULL,
  locked_by text NULL,
  locked_at timestamptz NULL,
  lease_until timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_deliveries PRIMARY KEY (id),
  CONSTRAINT uq_deliveries_delivery_id UNIQUE (delivery_id),
  CONSTRAINT uq_deliveries_idempotency_key UNIQUE (idempotency_key),
  CONSTRAINT fk_deliveries_lead
    FOREIGN KEY (lead_id) REFERENCES app_iseo_sales.leads (lead_id),
  CONSTRAINT ck_deliveries_status CHECK (
    status IN ('pending', 'processing', 'sent', 'retry', 'dead', 'cancelled')
  )
);

COMMENT ON TABLE app_iseo_sales.deliveries IS
  'Telegram/outbox delivery intents and results';

-- ---------------------------------------------------------------------------
-- 7) jobs
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  job_type text NOT NULL, -- pending_reminder, sheets_quota_defer, delivery_retry, …
  status text NOT NULL DEFAULT 'pending',
  priority int NOT NULL DEFAULT 100,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  available_at timestamptz NOT NULL DEFAULT now(),
  attempts int NOT NULL DEFAULT 0,
  max_attempts int NOT NULL DEFAULT 8,
  locked_by text NULL,
  locked_at timestamptz NULL,
  lease_until timestamptz NULL,
  dedupe_key text NULL,
  correlation_id text NULL,
  lead_id text NULL,
  last_error text NULL,
  completed_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_jobs PRIMARY KEY (id),
  CONSTRAINT ck_jobs_status CHECK (
    status IN ('pending', 'running', 'retry', 'completed', 'dead', 'cancelled')
  )
);

CREATE UNIQUE INDEX uq_jobs_dedupe_key
  ON app_iseo_sales.jobs (dedupe_key)
  WHERE dedupe_key IS NOT NULL;

COMMENT ON TABLE app_iseo_sales.jobs IS
  'Scheduled/retry work: reminders, defer, delivery_retry, reconciliation, projection';

-- ---------------------------------------------------------------------------
-- 8) idempotency_keys
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.idempotency_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  scope text NOT NULL, -- e.g. change_lead_status, enqueue_delivery
  idempotency_key text NOT NULL,
  request_hash text NULL,
  response_ref jsonb NULL,
  lead_id text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NULL,
  CONSTRAINT pk_idempotency_keys PRIMARY KEY (id),
  CONSTRAINT uq_idempotency_keys_scope_key UNIQUE (scope, idempotency_key)
);

-- ---------------------------------------------------------------------------
-- 9) errors
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.errors (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  app_component text NULL, -- operational, admin, toolkit
  workflow_version text NULL,
  n8n_execution_id text NULL,
  correlation_id text NULL,
  entity_type text NULL,
  entity_id text NULL,
  error_class text NULL, -- sheets_quota_exceeded, telegram_delivery_failed, …
  provider text NULL,
  code text NULL,
  http_status int NULL,
  stage text NULL,
  retryable boolean NOT NULL DEFAULT false,
  message_sanitized text NULL,
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  resolved boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_errors PRIMARY KEY (id)
);

-- Soft FK from deliveries.last_error_id
ALTER TABLE app_iseo_sales.deliveries
  ADD CONSTRAINT fk_deliveries_last_error
  FOREIGN KEY (last_error_id) REFERENCES app_iseo_sales.errors (id);

-- ---------------------------------------------------------------------------
-- 10) audit_logs
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  actor_type text NULL,
  actor_id text NULL,
  action text NOT NULL,
  entity_type text NULL,
  entity_id text NULL,
  correlation_id text NULL,
  result text NULL,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_audit_logs PRIMARY KEY (id),
  CONSTRAINT ck_audit_logs_result CHECK (
    result IS NULL OR result IN ('success', 'failure', 'rejected', 'noop')
  )
);

COMMENT ON TABLE app_iseo_sales.audit_logs IS
  'Operator/privilege-sensitive action trail; prefer append-only';

-- ---------------------------------------------------------------------------
-- 11) config (app flags only — no bot tokens / OAuth)
-- ---------------------------------------------------------------------------
CREATE TABLE app_iseo_sales.config (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  key text NOT NULL,
  value text NULL,
  value_type text NOT NULL DEFAULT 'string',
  description text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text NULL,
  is_secretish boolean NOT NULL DEFAULT false, -- marks sensitive app config (e.g. chat ids), still not OAuth
  CONSTRAINT pk_config PRIMARY KEY (id),
  CONSTRAINT uq_config_key UNIQUE (key),
  CONSTRAINT ck_config_value_type CHECK (
    value_type IN ('string', 'bool', 'int', 'json')
  )
);

COMMENT ON TABLE app_iseo_sales.config IS
  'DB-worthy application config only. Infrastructure secrets (bot token, OAuth) MUST NOT be stored.';

INSERT INTO mars_core.schema_migrations (schema_name, version, checksum)
VALUES ('app_iseo_sales', '0001_base_tables', NULL)
ON CONFLICT DO NOTHING;
