-- OPERATION SITE-002-PROD-1C-CATEGORY-MAPPING-BACKFILL-01
-- DRY RUN ONLY — DO NOT APPLY MANUALLY OUTSIDE THIS OPERATION
START TRANSACTION;
CREATE TABLE IF NOT EXISTS `oc_mars_1c_category_map` (
  `map_id` int unsigned NOT NULL AUTO_INCREMENT,
  `source_group_id` varchar(255) NOT NULL,
  `source_parent_group_id` varchar(255) DEFAULT NULL,
  `source_name` varchar(255) NOT NULL,
  `source_full_path` text NOT NULL,
  `source_full_path_hash` char(64) NOT NULL,
  `category_id` int unsigned NOT NULL,
  `confidence` varchar(64) NOT NULL,
  `status` varchar(64) NOT NULL,
  `last_seen_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`map_id`),
  UNIQUE KEY `uq_source_group_id` (`source_group_id`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_source_full_path_hash` (`source_full_path_hash`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `oc_mars_1c_category_map` (`source_group_id`,`source_parent_group_id`,`source_name`,`source_full_path`,`source_full_path_hash`,`category_id`,`confidence`,`status`,`last_seen_at`,`created_at`,`updated_at`) VALUES ('e0fd5c42-a3b8-11ea-8152-a85e4515c4f4',NULL,'ТЕХНОЛОГИЧЕСКОЕ ОБОРУДОВАНИЕ','ТЕХНОЛОГИЧЕСКОЕ ОБОРУДОВАНИЕ','a86a09e770a4a930ed702267d6860c0ea82ca4c3a44fa2bd168a7699e025977a',362,'HIGH_GUID_AND_PATH','active',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE `source_parent_group_id`=VALUES(`source_parent_group_id`),`source_name`=VALUES(`source_name`),`source_full_path`=VALUES(`source_full_path`),`source_full_path_hash`=VALUES(`source_full_path_hash`),`category_id`=VALUES(`category_id`),`confidence`=VALUES(`confidence`),`status`=VALUES(`status`),`last_seen_at`=UTC_TIMESTAMP(),`updated_at`=UTC_TIMESTAMP();
INSERT INTO `oc_mars_1c_category_map` (`source_group_id`,`source_parent_group_id`,`source_name`,`source_full_path`,`source_full_path_hash`,`category_id`,`confidence`,`status`,`last_seen_at`,`created_at`,`updated_at`) VALUES ('2adc2489-7c1a-11f1-aecc-581122cf362c','e0fd5c42-a3b8-11ea-8152-a85e4515c4f4','Мясоперерабатывающее','ТЕХНОЛОГИЧЕСКОЕ ОБОРУДОВАНИЕ > Мясоперерабатывающее','4904ebad8e42a9d1b8baf4e3178299437491e927712f48984e88ba87facb05e9',373,'HIGH_GUID_AND_PATH','active',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE `source_parent_group_id`=VALUES(`source_parent_group_id`),`source_name`=VALUES(`source_name`),`source_full_path`=VALUES(`source_full_path`),`source_full_path_hash`=VALUES(`source_full_path_hash`),`category_id`=VALUES(`category_id`),`confidence`=VALUES(`confidence`),`status`=VALUES(`status`),`last_seen_at`=UTC_TIMESTAMP(),`updated_at`=UTC_TIMESTAMP();
INSERT INTO `oc_mars_1c_category_map` (`source_group_id`,`source_parent_group_id`,`source_name`,`source_full_path`,`source_full_path_hash`,`category_id`,`confidence`,`status`,`last_seen_at`,`created_at`,`updated_at`) VALUES ('bac3dc26-7c19-11f1-aecc-581122cf362c','e0fd5c42-a3b8-11ea-8152-a85e4515c4f4','Электромеханическое','ТЕХНОЛОГИЧЕСКОЕ ОБОРУДОВАНИЕ > Электромеханическое','93386a648316cde15377e03942d9f271a20e4daddaa9c8d4acaef209c9fbc17e',375,'HIGH_GUID_AND_PATH','active',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE `source_parent_group_id`=VALUES(`source_parent_group_id`),`source_name`=VALUES(`source_name`),`source_full_path`=VALUES(`source_full_path`),`source_full_path_hash`=VALUES(`source_full_path_hash`),`category_id`=VALUES(`category_id`),`confidence`=VALUES(`confidence`),`status`=VALUES(`status`),`last_seen_at`=UTC_TIMESTAMP(),`updated_at`=UTC_TIMESTAMP();
INSERT INTO `oc_mars_1c_category_map` (`source_group_id`,`source_parent_group_id`,`source_name`,`source_full_path`,`source_full_path_hash`,`category_id`,`confidence`,`status`,`last_seen_at`,`created_at`,`updated_at`) VALUES ('e0b6bb6d-7c1a-11f1-aecc-581122cf362c','2adc2489-7c1a-11f1-aecc-581122cf362c','Слайсеры для мяса','ТЕХНОЛОГИЧЕСКОЕ ОБОРУДОВАНИЕ > Мясоперерабатывающее > Слайсеры для мяса','86a1ca500d7f0e08cecc93989cf9abe01d544b0d90461b07be6aaa4bfe8f4838',376,'HIGH_GUID_AND_PATH','active',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE `source_parent_group_id`=VALUES(`source_parent_group_id`),`source_name`=VALUES(`source_name`),`source_full_path`=VALUES(`source_full_path`),`source_full_path_hash`=VALUES(`source_full_path_hash`),`category_id`=VALUES(`category_id`),`confidence`=VALUES(`confidence`),`status`=VALUES(`status`),`last_seen_at`=UTC_TIMESTAMP(),`updated_at`=UTC_TIMESTAMP();
INSERT INTO `oc_mars_1c_category_map` (`source_group_id`,`source_parent_group_id`,`source_name`,`source_full_path`,`source_full_path_hash`,`category_id`,`confidence`,`status`,`last_seen_at`,`created_at`,`updated_at`) VALUES ('7e43262d-7c1a-11f1-aecc-581122cf362c','2adc2489-7c1a-11f1-aecc-581122cf362c','Мясорубки','ТЕХНОЛОГИЧЕСКОЕ ОБОРУДОВАНИЕ > Мясоперерабатывающее > Мясорубки','fd86cd735f2745c19a2a46d345d9ea05fad1c9f7c181638050095b6630c8fb1a',378,'HIGH_GUID_AND_PATH','active',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE `source_parent_group_id`=VALUES(`source_parent_group_id`),`source_name`=VALUES(`source_name`),`source_full_path`=VALUES(`source_full_path`),`source_full_path_hash`=VALUES(`source_full_path_hash`),`category_id`=VALUES(`category_id`),`confidence`=VALUES(`confidence`),`status`=VALUES(`status`),`last_seen_at`=UTC_TIMESTAMP(),`updated_at`=UTC_TIMESTAMP();
INSERT INTO `oc_mars_1c_category_map` (`source_group_id`,`source_parent_group_id`,`source_name`,`source_full_path`,`source_full_path_hash`,`category_id`,`confidence`,`status`,`last_seen_at`,`created_at`,`updated_at`) VALUES ('95003163-7c1a-11f1-aecc-581122cf362c','2adc2489-7c1a-11f1-aecc-581122cf362c','Пилы для мяса','ТЕХНОЛОГИЧЕСКОЕ ОБОРУДОВАНИЕ > Мясоперерабатывающее > Пилы для мяса','35e2036f7268b039047beb782a4e0573b35e8b0466aaafd6fa481a28392c45d9',379,'HIGH_GUID_AND_PATH','active',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE `source_parent_group_id`=VALUES(`source_parent_group_id`),`source_name`=VALUES(`source_name`),`source_full_path`=VALUES(`source_full_path`),`source_full_path_hash`=VALUES(`source_full_path_hash`),`category_id`=VALUES(`category_id`),`confidence`=VALUES(`confidence`),`status`=VALUES(`status`),`last_seen_at`=UTC_TIMESTAMP(),`updated_at`=UTC_TIMESTAMP();
INSERT INTO `oc_mars_1c_category_map` (`source_group_id`,`source_parent_group_id`,`source_name`,`source_full_path`,`source_full_path_hash`,`category_id`,`confidence`,`status`,`last_seen_at`,`created_at`,`updated_at`) VALUES ('41a86281-7c1b-11f1-aecc-581122cf362c','bac3dc26-7c19-11f1-aecc-581122cf362c','Хлеборезки','ТЕХНОЛОГИЧЕСКОЕ ОБОРУДОВАНИЕ > Электромеханическое > Хлеборезки','fc4ee236dbbf6414ea1bce91d121393b7ee3a8c6bbeb568af11de0509bc892eb',380,'HIGH_GUID_AND_PATH','active',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE `source_parent_group_id`=VALUES(`source_parent_group_id`),`source_name`=VALUES(`source_name`),`source_full_path`=VALUES(`source_full_path`),`source_full_path_hash`=VALUES(`source_full_path_hash`),`category_id`=VALUES(`category_id`),`confidence`=VALUES(`confidence`),`status`=VALUES(`status`),`last_seen_at`=UTC_TIMESTAMP(),`updated_at`=UTC_TIMESTAMP();
COMMIT;
