-- mars_core platform tables + seed apps
-- Prerequisites: core/0001_roles_and_schemas.sql

-- 1) schema_migrations ledger
CREATE TABLE mars_core.schema_migrations (
  schema_name text NOT NULL,
  version text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now(),
  checksum text NULL,
  CONSTRAINT pk_schema_migrations PRIMARY KEY (schema_name, version)
);

COMMENT ON TABLE mars_core.schema_migrations IS
  'Applied migration versions per schema (human/Toolkit ledger; not Flyway-mandatory)';

-- 2) apps registry
CREATE TABLE mars_core.apps (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  app_key text NOT NULL,
  schema_name text NOT NULL,
  display_name text NOT NULL,
  status text NOT NULL DEFAULT 'planned',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT pk_apps PRIMARY KEY (id),
  CONSTRAINT uq_apps_app_key UNIQUE (app_key),
  CONSTRAINT uq_apps_schema_name UNIQUE (schema_name),
  CONSTRAINT ck_apps_status CHECK (status IN ('active', 'retired', 'planned'))
);

COMMENT ON TABLE mars_core.apps IS 'Registered MARS bot applications and their schemas';

-- 3) data_contract_versions
CREATE TABLE mars_core.data_contract_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  app_id bigint NOT NULL,
  contract_key text NOT NULL,
  version text NOT NULL,
  status text NOT NULL DEFAULT 'draft',
  activated_at timestamptz NULL,
  deactivated_at timestamptz NULL,
  notes text NULL,
  CONSTRAINT pk_data_contract_versions PRIMARY KEY (id),
  CONSTRAINT fk_data_contract_versions_app
    FOREIGN KEY (app_id) REFERENCES mars_core.apps (id),
  CONSTRAINT uq_data_contract_versions_app_key_ver
    UNIQUE (app_id, contract_key, version),
  CONSTRAINT ck_data_contract_versions_status
    CHECK (status IN ('draft', 'active', 'retired'))
);

-- 4) workflow_releases
CREATE TABLE mars_core.workflow_releases (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  app_id bigint NOT NULL,
  workflow_family text NOT NULL, -- e.g. operational_intake, admin_commands
  n8n_workflow_id text NULL,
  release_version text NOT NULL,
  data_contract_version text NULL,
  status text NOT NULL DEFAULT 'candidate',
  git_export_hash text NULL,
  activated_at timestamptz NULL,
  deactivated_at timestamptz NULL,
  notes text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pk_workflow_releases PRIMARY KEY (id),
  CONSTRAINT fk_workflow_releases_app
    FOREIGN KEY (app_id) REFERENCES mars_core.apps (id),
  CONSTRAINT ck_workflow_releases_status
    CHECK (status IN ('candidate', 'active', 'retired', 'rollback'))
);

COMMENT ON COLUMN mars_core.workflow_releases.workflow_family IS
  'Logical family e.g. operational_intake, admin_commands';

-- One active release per (app_id, workflow_family)
CREATE UNIQUE INDEX uq_workflow_releases_one_active_per_family
  ON mars_core.workflow_releases (app_id, workflow_family)
  WHERE status = 'active';

CREATE INDEX idx_workflow_releases_app_status
  ON mars_core.workflow_releases (app_id, status);

-- Seed apps
INSERT INTO mars_core.apps (app_key, schema_name, display_name, status, metadata)
VALUES
  (
    'app_iseo_sales',
    'app_iseo_sales',
    'i-SEO Sales Manager',
    'planned',
    '{"product_pack":"iseo-sales-manager-bot"}'::jsonb
  ),
  (
    'app_seo_content',
    'app_seo_content',
    'MetaBOT SEO Content Agent',
    'planned',
    '{"product_pack":"metabot-seo-content-agent","tables":"none_v1_placeholder"}'::jsonb
  )
ON CONFLICT (app_key) DO NOTHING;

INSERT INTO mars_core.schema_migrations (schema_name, version, checksum)
VALUES ('mars_core', '0002_mars_core', NULL)
ON CONFLICT DO NOTHING;
