START TRANSACTION;
DELETE FROM fp02_postmeta WHERE post_id=1033 AND meta_key IN ('specialist_role', '_specialist_role');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, 'specialist_role', 'Психолог, EMDR терапевт, телесно-ориентированный терапевт');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, '_specialist_role', 'field_fp02_specialist_role');
DELETE FROM fp02_postmeta WHERE post_id=1033 AND meta_key IN ('specialist_experience', '_specialist_experience');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, 'specialist_experience', 'Опыт — 2,5 года');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, '_specialist_experience', 'field_fp02_specialist_experience');
DELETE FROM fp02_postmeta WHERE post_id=1033 AND meta_key IN ('specialist_specialty', '_specialist_specialty');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, 'specialist_specialty', '<p>Практический психолог, телесно-ориентированный психотерапевт, EMDR/ДПДГ терапевт</p>');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, '_specialist_specialty', 'field_fp02_specialist_specialty');
DELETE FROM fp02_postmeta WHERE post_id=1033 AND meta_key IN ('specialist_education', '_specialist_education');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, 'specialist_education', '2023-2024 АНО ДПО «НАДПО»<br>\n2024 Институт Психотерапии и Клинической Психологии (повышение квалификации)<br>\n2025 Московский Институт Милтона Эриксона (ДПДГ)<br>\n2025 по настоящее время МГИ Московский Гештальт Институт, 2 ступень');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, '_specialist_education', 'field_fp02_specialist_education');
DELETE FROM fp02_postmeta WHERE post_id=1033 AND meta_key IN ('specialist_specialization', '_specialist_specialization');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, 'specialist_specialization', 'Психосоматика и телесная психотерапия<br>\nДессенсибилизация и переработка движением глаз<br>\nСертификат спецкурса «Психиатрия для психологов» от GATLA');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, '_specialist_specialization', 'field_fp02_specialist_specialization');
DELETE FROM fp02_postmeta WHERE post_id=1033 AND meta_key IN ('specialist_principles', '_specialist_principles');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, 'specialist_principles', '<p>Дарья применяет методы и техники из нескольких психотерапевтических направлений: телесно-ориентированной терапии, гештальт терапии и метода EMDR/ДПДГ (дессенсибилизация и переработка движением глаз), что позволяет подобрать комплексный и индивидуализированный подход для улучшения психического состояния клиента.</p>');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, '_specialist_principles', 'field_fp02_specialist_principles');
DELETE FROM fp02_postmeta WHERE post_id=1033 AND meta_key IN ('specialist_certificates', '_specialist_certificates');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, 'specialist_certificates', 'a:3:{i:0;i:1853;i:1;i:1855;i:2;i:1854;}');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1033, '_specialist_certificates', 'field_fp02_specialist_certificates');
DELETE FROM fp02_postmeta WHERE post_id=1031 AND meta_key IN ('specialist_role', '_specialist_role');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1031, 'specialist_role', 'Аддиктолог, интервенционист');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1031, '_specialist_role', 'field_fp02_specialist_role');
DELETE FROM fp02_postmeta WHERE post_id=1031 AND meta_key IN ('specialist_additional', '_specialist_additional');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1031, 'specialist_additional', '<p>Раздел находится в подготовке. Здесь будет опубликована расширенная информация о специалисте.</p>');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1031, '_specialist_additional', 'field_fp02_specialist_additional');
DELETE FROM fp02_postmeta WHERE post_id=1032 AND meta_key IN ('specialist_role', '_specialist_role');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1032, 'specialist_role', 'Психолог, преподаватель психологии, гештальт-терапевт');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1032, '_specialist_role', 'field_fp02_specialist_role');
DELETE FROM fp02_postmeta WHERE post_id=1032 AND meta_key IN ('specialist_additional', '_specialist_additional');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1032, 'specialist_additional', '<p>Раздел находится в подготовке. Здесь будет опубликована расширенная информация о специалисте.</p>');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1032, '_specialist_additional', 'field_fp02_specialist_additional');
DELETE FROM fp02_postmeta WHERE post_id=1097 AND meta_key IN ('specialist_role', '_specialist_role');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1097, 'specialist_role', 'Сертифицированный гонг-мастер, звукотерапевт и преподаватель Кундалини йоги.');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1097, '_specialist_role', 'field_fp02_specialist_role');
DELETE FROM fp02_postmeta WHERE post_id=1097 AND meta_key IN ('specialist_additional', '_specialist_additional');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1097, 'specialist_additional', '<p>Раздел находится в подготовке. Здесь будет опубликована расширенная информация о специалисте.</p>');
INSERT INTO fp02_postmeta (post_id, meta_key, meta_value) VALUES (1097, '_specialist_additional', 'field_fp02_specialist_additional');
COMMIT;
